# Hands-On

Hands-On ini digunakan pada kegiatan Workshop Data Science 2022, Universitas Gunadarma

# Pertemuan 5

Pertemuan 5 (lima) pada  Workshop Data Science 2022, Universitas Gunadarma menyampaikan materi mengenai Mengumpulkan Data, Menelaah Data dengan metode Statistik

# Pengambilan Data dari API Kaggle
---
Salah satu portal yang menyediakan dataset untuk project Data Science adalah Kaggle (https://www.kaggle.com/).
Pada latihan ini, silakan peserta mengunduh dataset mengenai bunga Iris dengan menggunakan kata kunci: "iris species" yang disediakan oleh UCI Machine Learning (UCIML)

**1. Install Modul kaggle:**

In [ ]:
# Install modul kaggle secara inline (di dalam notebook)
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\user\anaconda3\lib\site-packages (1.5.12)
Requirement already satisfied: certifi in c:\users\user\anaconda3\lib\site-packages (from kaggle) (2020.12.5)
Requirement already satisfied: urllib3 in c:\users\user\anaconda3\lib\site-packages (from kaggle) (1.26.4)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\lib\site-packages (from kaggle) (4.59.0)
Requirement already satisfied: python-slugify in c:\users\user\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: six>=1.10 in c:\users\user\anaconda3\lib\site-packages (from kaggle) (1.15.0)
Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (from kaggle) (2.25.1)
Requirement already satisfied: python-dateutil in c:\users\user\anaconda3\lib\site-packages (from kaggle) (2.8.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\user\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\user\anaconda3\lib\site-packages (from requests->kaggle) (4.0.0)

In [ ]:
# Install modul kaggle secara eksternal melalui anaconda prompt:

![image.png](attachment:image.png)

**2. Create Token API kaggle:**

![image.png](attachment:image.png)

1. Login Kaggle.com 
2. Kemudian pada menu Profile --> Account
3. Klik Create New Api Token 
4. Maka akan terdownload file kaggle.json

![image.png](attachment:image.png)

Kaggle API secara default mengasumsikan bahwa file kaggle.json tersebut berada di dalam folder: 
* ~/.kaggle/ (Linux/Mac)  
* C:\Users\<Windows-username>\.kaggle\ (Windows)

Jika folder tersebut belum ada:
1. Buat folder di direktori C:\Users\<Windows-username>\.kaggle\
2. letakkan file kaggle.json kedalam folder tersebut

**3. Download Dataset dari Kaggle:**

![image.png](attachment:image.png)
<div class="text-center">
    Dokumentasi Kaggle Commands selengkapnya <a href="https://github.com/Kaggle/kaggle-api#datasets">Disini</a>
</div>

In [ ]:
# Mencari dataset yang tersedia di kaggle --> pilih data provider dari UCIML
!kaggle datasets list -s "Iris Species"

ref                                                      title                                                size  lastUpdated          downloadCount  voteCount  usabilityRating
-------------------------------------------------------  --------------------------------------------------  -----  -------------------  -------------  ---------  ---------------
uciml/iris                                               Iris Species                                          4KB  2016-09-27 07:38:05         223600       2660  0.7941176
gpiosenka/100-bird-species                               315 Bird Species - Classification                     1GB  2021-11-02 18:32:27          16055        571  0.88235295
slothkong/10-monkey-species                              10 Monkey Species                                   547MB  2018-06-28 01:38:58          17630        412  0.8125
arshid/iris-flower-dataset                               Iris Flower Dataset                                 1010B  2018-03-22 15:18:06          40262        367  0.8235294
arslanali4343/iris-species                               Iris Species                                          2KB  2020-07-02 06:09:09             48         13  0.5625
veeralakrishna/200-bird-species-with-11788-images        200 Bird Species with 11,788 Images                   1GB  2020-01-10 13:57:20           2345         72  0.9375
akash2907/bird-species-classification                    bird species classification                           1GB  2018-09-30 00:47:56           3463         62  0.75
olgabelitskaya/flower-color-images                       Flower Color Images                                  50MB  2020-10-01 22:48:07           8331        161  0.75
vikrishnan/iris-dataset                                  Iris Dataset                                         999B  2017-08-03 16:00:44           2888         26  0.7647059
rtatman/iris-dataset-json-version                        Iris Dataset (JSON Version)                           1KB  2018-04-06 20:21:31           5603         43  0.75
gpiosenka/butterfly-images40-species                     Butterfly Image Classification 50 species           842MB  2021-07-05 00:54:36            512         15  0.88235295
b'sripaadsrinivasan/fish-species-image-data                \xf0\x9f\x90\x9f\xf0\x9f\x90\x9f\xf0\x9f\x90\x9fFish Species Image Data                            1GB  2020-11-09 04:30:38            933         34  1.0              '
smritisingh1997/species-segmentation-using-iris-dataset  Species Segmentation using Iris dataset              896B  2020-05-13 20:44:51             75          5  0.7058824
larusso94/shark-species                                  Shark species                                       598MB  2020-10-30 21:22:41            184         15  0.875
saife245/malaria-plasmodium-vivax-specie                 Malaria: Plasmodium Vivax Species                    36MB  2020-06-15 09:36:50             69         13  1.0
kedarsai/bird-species-classification-220-categories      Bird Species Classification 200 Categories            1GB  2020-08-22 15:19:40            171          5  0.875
saife245/malaria-plasmodium-falciparum-species           Malaria: Plasmodium Falciparum Species              121MB  2020-06-15 10:09:22            105         16  0.875
souravbhattacharya10/irisdataset                         IrisDataset                                           1KB  2019-04-15 11:00:50            408          8  0.7647059
sapal6/bird-speciestiny                                  Bird species(tiny)                                    7MB  2021-06-08 02:11:47            175          8  0.7941176
saife245/malaria-parasite-image-malaria-species          Malaria Parasite Image (Different Malaria Species)    2GB  2020-06-07 07:36:06            326         19  0.8125

In [ ]:
# Download dan ekstrak dataset, secara default akan berada dalam satu direktori dengan notebook ini
!kaggle datasets download uciml/iris --unzip

Downloading iris.zip to C:\Users\User\Microcred\Persiapan

  0%|          | 0.00/3.60k [00:00<?, ?B/s]
100%|##########| 3.60k/3.60k [00:00<00:00, 665kB/s]

Atau bisa juga menggunakan link dari kaggle

# Latihan (1)

Silahkan Download sebuah dataset menggunakan API Kaggle

In [ ]:
#Latihan (1)
#Langkah nya seperti contoh diatas

### PENGGUNAAN LIBRARY PANDAS dan NUMPY

Pada materi ini, peserta sudah mendapatkan pemahaman mengenai data dan dataset. Penggunaan library pada Python memberikan kemudahan dalam proses data understanding. Beberapa library yang digunakan adalah library Pandas dan Numpy.

# Latihan (2)

Lakukan import Library Pandas dan Library Numpy

In [ ]:
#Latihan(2)
#Import Library Pandas

<...............>

#Import Library Numpy

<...............>

### DATAFRAME

DataFrame adalah struktur data 2 dimensi yang berbentuk tabular (mempunyai baris dan kolom). Hampir semua data tidak hanya memiliki 1 kolom tetapi lebih dari 1 kolom, sehingga lebih cocok menggunakan pandas DataFrame untuk mengolahnya.

Penggunaan dataframe pada Python dengan menggunakan syntaks: df.

# Latihan (3)

Panggil file (load dataset) dengan format .csv untuk dataset mengenai bunga Iris yang sudah peserta unduh dari Kaggle, dan akan disimpan di dalam dataframe df. Lalu tampilkan 5 baris awal dataset dengan function head()

In [ ]:
#latihan(3)
#Panggil file (load file bernama Iris.csv) dan simpan dalam dataframe Lalu tampilkan 5 baris awal dataset dengan function head()

<...............>

# Telaah Data

Pada telaah data, dapat dilakukan untuk mengetahui:
- tipe data dari setiap kolom
- deskripsi statistik data

# Latihan (4)

Tampilkan tipe data dari kolom yang ada pada dataset

In [ ]:
#latihan(4)
#Tampilkan tipe data dari kolom yang ada pada dataset

<...............>

# Latihan (5)

Apakah tipe Data dari kolom berikut ini: (silakan diisi pada cell di bawah ini)

In [ ]:
#Latihan (5)
#Tipe Data dari kolom yang ada di dataset

#Kolom  "Id" memiliki tipe data =  <isikan jawaban di sini>
#Kolom "SepalLengthCm" memiliki tipe data =  <isikan jawaban di sini>
#Kolom "Species" memiliki tipe data =  <isikan jawaban di sini>

# Latihan (6)

Hitunglah ukuran (jumlah baris dan kolom) dari dataset. Dengan menggunakan method function

In [ ]:
#Latihan (6)
#Hitung ukuran (jumlah baris dan kolom) dari dataset

<...............>

# Latihan (7)

Berapakah jumlah baris, dan jumlah kolom pada dataset? (silakan diisi pada cell di bawah ini)

In [ ]:
#Latihan (7)

#Jumlah Baris pada dataset adalah =  <isikan jawaban di sini>

#Jumlah kolom pada dataset adalah =  <isikan jawaban di sini>

# Latihan (8)

Tampilkan data yang hanya berisi kolom "Id" dan kolom "Species" dalam bentuk dataframe.

In [ ]:
#Latihan (8)
#Tampilkan data untuk kolom "Id" dan kolom "Species" dalam bentuk dataframe

<...............>

# Latihan (9)

Tampilkan data dengan dataframe, dan data yang ditampilkan adalah data pada baris dengan indeks 0 (nol) sampai dengan indeks 9 (sembilan)

In [ ]:
#Latihan (9)
#Tampilkan data dengan dataframe, dan data yang ditampilkan adalah baris dengan indeks 0 (nol) sampai dengan indeks 9 (sembilan)

<...............>

# Latihan (10)

Tampilkan data hanya kolom "Id" dan kolom "Species" dengan dataframe, dan yang ditampilkan adalah data pada baris dengan indeks 11 (sebelas) sampai dengan indeks 15 (limabelas)

In [ ]:
#Latihan (10)
#Tampilkan data hanya kolom "Id" dan kolom "Species", pada baris dengan indeks 11 (sebelas) sampai dengan indeks 15 (limabelas)

<...............>

# Latihan (11)

Pada DataFrame dapat menampilkan beberapa baris pertama/terakhir dari dataset yang di load. Gunakan Method head() dan tail().

Latihan: Tampilkan data pada 8 (delapan) baris pertama dari dataset, dengan dataframe.

In [ ]:
#Latihan (11)
#Tampilkan data pada 8 (delapan) baris pertama dari dataset, dengan dataframe

<...............>

# Latihan (12)

Tampilkan data pada 3 (tiga) baris terakhir dari dataset, dengan dataframe.

In [ ]:
#Latihan (12)
#Tampilkan data pada 3 (tiga) baris terakhir dari dataset, dengan dataframe

<...............>

# Deskripsi Statistik Data

DataFrame method describe() menampilkan statistik dasar setiap kolom data yang bertipe numerik, mencakup banyaknya data (count), rerata aritmetik (mean), simpangan baku (std), nilai terkecil (min), kuartil pertama (25%), kuartil kedua/median (50%), kuartil ketiga (75%), dan nilai terbesar (max).

# Latihan (13)

Hitung korelasi dari dataset. Dengan menggunakan method function

In [ ]:
#Latihan (13)
#Hitung korelasi dataset

<...............>

# Latihan (14)

Berdasarkan pada perhitungan korelasi di Latihan (11), apakah yang dapat Bapak/Ibu simpulkan sementara? Silakan tuliskan simpulan sementara Bapak/Ibu pada cell di bawah ini.

In [ ]:
#latihan (14)
#Simpulan Sementara Hasil Korelasi di latihan (13)

<........Berikan Kesimpulan disini...........>

# Latihan (15)

Hitung korelasi untuk kolom berikut ini: PetalLengthCm, PetalWidthCm

In [ ]:
#Latihan (15)
#Hitung korelasi dataset untuk kolom PetalLengthCm, PetalWidthCm

<...............>

# Latihan (16)

Method "describe" secara otomatis melakukan komputasi statistik untuk semua continous variable. Secara default "describe" melakukan ignore terhadap variabel bertype objek.

Komputasi statistik yang dilakukan terdiri dari: count, mean, std, min, max, 25%, 75%, max.

Latihan: Gunakan method describe pada dataset yang sudah di load untuk semua continous variabel. (Dataset Iris.csv)

In [ ]:
#Latihan (16)
# Penggunaan Metode describe untuk komputasi statistik

<...............>

# Latihan (17)

Gunakan method describe pada dataset yang sudah di load untuk data bertype objek. (Dataset Iris.csv)

In [ ]:
#Latihan (17)
#Gunakan method describe pada dataset yang sudah di load untuk data bertype objek

<...............>

# Latihan 18

Gunakan method describe pada dataset yang sudah di load untuk semua type data (continous variabel dan type object).

In [ ]:
#Latihan (18)
#Gunakan method describe pada dataset yang sudah di load untuk semua type data

<...............>

# Latihan (19)

Hitunglah nilai mean dari dataset.

In [ ]:
#Latihan (19)
#Hitung nilai Mean dari dataset

<...............>

# Latihan (20)

Hitung nilai mean dari dataset untuk kolom PetalLengthCm.

In [ ]:
#Latihan (20)
#Hitung nilai Mean untuk kolom PetalLengthCm

<...............>

# Latihan (21)

Carilah nilai minimal dari dataset untuk kolom SepalWidthCm.

In [ ]:
#Latihan (21)
#Cari nilai minimal untuk kolom SepalWidthCm

<...............>

# Method Groupby

Method groupby memungkinkan analisis dilakukan secara per kelompok nilai atribut tertentu.

# Latihan (22)

Hitunglah nilai mean dari dataset untuk kolom SepalLengthCm per Species dengan menggunakan metode groupby.

In [ ]:
#Latihan (22)
#Hitung nilai mean dari dataset untuk SepalLengthCm per Species dengan metode groupby

<...............>

# Method Value Count

value_counts() menghasilkan frekuensi setiap nilai unik di dalam kolom, dan yang tertinggi count-nya adalah merupakan modus pada kolom tersebut.

# Latihan (23)

Hitunglah frekuensi pada kolom 'Species' dengan menggunakan metode value_counts().

In [ ]:
#Latihan (23)
#Hitung frekuensi pada kolom 'Species' dengan menggunakan metode value_counts()

<...............>

# Latihan (24)

Tampilkan perhitungan frekuensi pada kolom 'Species' dengan menggunakan metode value_counts() dalam bentuk dataframe.

In [ ]:
#Latihan (24)
#Perhitungan frekuensi pada kolom 'Species' dengan menggunakan metode value_counts() dalam bentuk dataframe

<...............>

# Latihan (25)

Hitunglah frekuensi pada kolom 'PetalLenghCm' dengan menggunakan metode value_counts() dan dalam bentuk dataframe.

In [ ]:
#Latihan (25)
# Hitung frekuensi pada kolom 'PetalLenghCm' dengan menggunakan metode value_counts()

<...............>