<div class="alert alert-block alert-info">
<h2>Daftar Isi: </h2>
<h3>Transformasi Data</h3>
<h5>Imputasi:</h5>
    <ol>
    <li>Imputasi Mean atau Median</li>
    <li>Imputasi Nilai Suka-suka (Arbitrary)</li>
        Imputasi End of Tail
        Imputasi Frequent Category/Modus
        Imputasi Random Sample
        Imputasi Nilai Nol/Konstanta
        Imputasi Regresi: Deterministik
    </ol>
<h5>Trimming vs Winsorizing</h5>
<h5>Binning</h5>
<h5>Scaling (Penskalaan):</h5>
     <ol>
        <li>Scaling: Normalisasi</li>
        <li>Scaling: Standardisasi</li>
     </ol>
</div>

# Mengkonstruksi Data
---

## Imputasi
---

Imputasi adalah Mengganti nilai/data yang hilang (missing value; NaN; blank) dengan nilai pengganti.

Teknik imputasi berdasarkan tipe data, terdiri dari:
1. Tipe data Variabel Numerik, dengan cara:
   - Imputasi mean atau median.
   - Imputasi nilai suka-suka (arbitrary).
   - Imputasi nilai/data ujung (end of tail).


2. Tipe data Variabel Kategorik, dengan cara:
   - Imputasi kategori yang sering muncul.
   - Tambah kategori yang hilang.

### Imputasi Mean atau Median
___

Merupakan teknik yang digunakan mengganti nilai/data yang hilang untuk tipe data numerik, dan cocok untuk data missing completely at random (MCAR).

In [2]:
#Import pandas dan numpy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

Mengawali Hands-On ini, import library Pandas dan library Numpy telah dilakukan diawal, sehingga pada contoh-contoh code dibawah, sudah tidak dilakukan import library Pandas dan library Numpy.

In [3]:
#Contoh 1 - Imputasi MEAN
#Masukkan data

kolom = {'col1' : [2, 9, 19],
        'col2' : [5, np.nan, 17],
        'col3' : [3, 9, np.nan],
        'col4' : [6, 0, 9],
        'col5' : [np.nan, 7, np.nan]}

data = pd.DataFrame(kolom)

#pd.DataFrame() --> fungsi mengubah menjadi dataframe

In [4]:
#Contoh 1 - Imputasi MEAN
#Tampilkan nilai yang ada pada variabel 'kolom' dalam bentuk dataframe 'data'

data

   col1  col2  col3  col4  col5
0     2   5.0   3.0     6   NaN
1     9   NaN   9.0     0   7.0
2    19  17.0   NaN     9   NaN

Tampak pada variabel 'kolom' terdapat data yang hilang (NaN), misal pada baris di indeks=1 kolom=col2. Maka nilai yang hilang (NaN) dapat diberikan nilai, salah satunya dengan menggunakan teknik imputasi MEAN.

In [5]:
#Contoh 1 - Imputasi MEAN
# Mengganti missing value dengan mean()

data.fillna(data.mean())

   col1  col2  col3  col4  col5
0     2   5.0   3.0     6   7.0
1     9  11.0   9.0     0   7.0
2    19  17.0   6.0     9   7.0

Setelah dilakukan imputasi MEAN, terlihat pada data baris di indeks=1 kolom=col2 telah terisi nilai yang didapatkan dari nilai mean (rata-rata).

In [6]:
#Contoh 2 - Imputasi MEAN
#Masukkan data

umur = {'umur' : [29, 43,  np.nan, 25, 34, np.nan, 50]}

#Ubah ke dataframe

data = pd.DataFrame(umur)

#Tampilkan nilai yang ada pada variabel 'umur' dalam bentuk dataframe 'data'

data

   umur
0  29.0
1  43.0
2   NaN
3  25.0
4  34.0
5   NaN
6  50.0

Tampak pada variabel 'umur' terdapat data yang hilang (NaN), misal umur yang ada pada baris di indeks= 2. Maka nilai yang hilang (NaN) dapat diberikan nilai, salah satunya dengan menggunakan teknik imputasi MEAN.

In [7]:
#Contoh 2 - Imputasi MEAN
#Mengganti missing value dengan mean pada kolom umur

data.fillna(data.mean())

#data.fillna() --> fungsi mengganti missing value

   umur
0  29.0
1  43.0
2  36.2
3  25.0
4  34.0
5  36.2
6  50.0

Setelah dilakukan imputasi MEAN, pada data umur yang ada pada baris di indeks= 2 telah memiliki nilai yang diperoleh dari nilai mean (rata-rata)

### Imputasi Nilai Suka-suka (Arbitrary)
---

Imputasi nilai suka-suka (Arbitrary) juga merupakan salah satu teknik imputasi yang dapat digunakan untuk menggantikan nilai/data yang hilang. Teknik ini juga cocok untuk digunakan bagi tipe data numerik.

In [8]:
#Contoh 1 - Imputasi ARBITRARY
#Masukkan  data

umur = {'umur' : [29, 43,  np.nan, 25, 34, np.nan, 50]}

#Ubah ke dataframe

data = pd.DataFrame(umur)

#Tampilkan nilai yang ada pada variabel 'umur' dalam bentuk dataframe 'data'

data

   umur
0  29.0
1  43.0
2   NaN
3  25.0
4  34.0
5   NaN
6  50.0

Tampak pada variabel 'umur' terdapat nilai yang hilang (NaN), misalkan nilai umur yang ada pada baris di indeks= 2.

In [9]:
#Contoh 1 - Imputasi ARBITRARY
#Mengatasi nilai missing value dengan imputasi suka-suka
#Nilai suka-suka yang diberikan pada contoh adalah 99

data.fillna(99)

   umur
0  29.0
1  43.0
2  99.0
3  25.0
4  34.0
5  99.0
6  50.0

Setelah dilakukan imputasi ARBITRARY, data umur pada baris 2 telah memiliki nilai yaitu 99, sesuai dengan nilai suka-suka yang telah diberikan.

### Imputasi End of Tail

Imputasi End of Tail juga termasuk salah satu teknik untuk mengganti data/nilai yang hilang dan digunakan untuk tipe data numerik.

In [10]:
#Contoh 1 - Imputasi END OF TAIL
#masukkan data

umur = {'umur' : [29, 43,  np.nan, 25, 34, np.nan, 50]}

#Data dalam bentuk dataframe
data = pd.DataFrame(umur)

#Tampilkan nilai pada variabel 'umur' dalam bentuk dataframe

data

   umur
0  29.0
1  43.0
2   NaN
3  25.0
4  34.0
5   NaN
6  50.0

Tampak pada variabel 'umur' terdapat nilai yang hilang (NaN), misalkan nilai umur yang ada pada baris di indeks= 2.

In [11]:
pip install feature_engine

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: feature_engine in /usr/local/lib/python3.7/dist-packages (0.3.0)
Requirement already satisfied: scikit-learn>=0.18.1 in /usr/local/lib/python3.7/dist-packages (from feature_engine) (1.0.2)
Requirement already satisfied: statsmodels>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from feature_engine) (0.13.2)
Requirement already satisfied: numpy>=1.12.1 in /usr/local/lib/python3.7/dist-packages (from feature_engine) (1.21.6)
Requirement already satisfied: pytest==4.3.1 in /usr/local/lib/python3.7/dist-packages (from feature_engine) (4.3.1)
Requirement already satisfied: numpydoc>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from feature_engine) (1.4.0)
Requirement already satisfied: scipy>=0.19.0 in /usr/local/lib/python3.7/dist-packages (from feature_engine) (1.7.3)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.7/dist-packages (from feature_engine) (1.3.5)
Requirement already satisfied: pluggy>=0.7 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature_engine) (0.7.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature_engine) (22.1.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature_engine) (1.4.1)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature_engine) (1.11.0)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature_engine) (8.14.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature_engine) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature_engine) (57.4.0)
Requirement already satisfied: sphinx>=3.0 in /usr/local/lib/python3.7/dist-packages (from numpydoc>=0.6.0->feature_engine) (5.1.1)
Requirement already satisfied: Jinja2>=2.10 in /usr/local/lib/python3.7/dist-packages (from numpydoc>=0.6.0->feature_engine) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2>=2.10->numpydoc>=0.6.0->feature_engine) (2.0.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.0->feature_engine) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.0->feature_engine) (2.8.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18.1->feature_engine) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18.1->feature_engine) (1.1.0)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (2.6.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (4.12.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (1.1.5)
Requirement already satisfied: sphinxcontrib-applehelp in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (1.0.2)
Requirement already satisfied: imagesize in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (1.4.1)
Requirement already satisfied: requests>=2.5.0 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (2.23.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (2.0.0)
Requirement already satisfied: babel>=1.3 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (2.10.3)
Requirement already satisfied: sphinxcontrib-jsmath in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (1.0.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (0.7.12)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (2.2.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (21.3)
Requirement already satisfied: docutils<0.20,>=0.14 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (0.17.1)
Requirement already satisfied: sphinxcontrib-qthelp in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (1.0.3)
Requirement already satisfied: sphinxcontrib-devhelp in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (1.0.2)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (3.8.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.5.0->sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.5.0->sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.5.0->sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.5.0->sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (3.0.4)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.7/dist-packages (from statsmodels>=0.8.0->feature_engine) (0.5.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->sphinx>=3.0->numpydoc>=0.6.0->feature_engine) (3.0.9)

In [4]:
pip install feature-engine==0.3.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: feature-engine==0.3.0 in /usr/local/lib/python3.7/dist-packages (0.3.0)
Requirement already satisfied: scipy>=0.19.0 in /usr/local/lib/python3.7/dist-packages (from feature-engine==0.3.0) (1.7.3)
Requirement already satisfied: pytest==4.3.1 in /usr/local/lib/python3.7/dist-packages (from feature-engine==0.3.0) (4.3.1)
Requirement already satisfied: numpydoc>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from feature-engine==0.3.0) (1.4.0)
Requirement already satisfied: numpy>=1.12.1 in /usr/local/lib/python3.7/dist-packages (from feature-engine==0.3.0) (1.21.6)
Requirement already satisfied: statsmodels>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from feature-engine==0.3.0) (0.13.2)
Requirement already satisfied: pandas>=0.23.0 in /usr/local/lib/python3.7/dist-packages (from feature-engine==0.3.0) (1.3.5)
Requirement already satisfied: scikit-learn>=0.18.1 in /usr/local/lib/python3.7/dist-packages (from feature-engine==0.3.0) (1.0.2)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature-engine==0.3.0) (1.11.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature-engine==0.3.0) (57.4.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature-engine==0.3.0) (1.15.0)
Requirement already satisfied: pluggy>=0.7 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature-engine==0.3.0) (0.7.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature-engine==0.3.0) (8.14.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature-engine==0.3.0) (22.1.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.7/dist-packages (from pytest==4.3.1->feature-engine==0.3.0) (1.4.1)
Requirement already satisfied: Jinja2>=2.10 in /usr/local/lib/python3.7/dist-packages (from numpydoc>=0.6.0->feature-engine==0.3.0) (2.11.3)
Requirement already satisfied: sphinx>=3.0 in /usr/local/lib/python3.7/dist-packages (from numpydoc>=0.6.0->feature-engine==0.3.0) (5.1.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2>=2.10->numpydoc>=0.6.0->feature-engine==0.3.0) (2.0.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.0->feature-engine==0.3.0) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23.0->feature-engine==0.3.0) (2.8.2)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18.1->feature-engine==0.3.0) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18.1->feature-engine==0.3.0) (3.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (21.3)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (0.7.12)
Requirement already satisfied: sphinxcontrib-applehelp in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (1.0.2)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (4.12.0)
Requirement already satisfied: sphinxcontrib-jsmath in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (1.0.1)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (2.2.0)
Requirement already satisfied: docutils<0.20,>=0.14 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (0.17.1)
Requirement already satisfied: imagesize in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (1.4.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (2.0.0)
Requirement already satisfied: sphinxcontrib-devhelp in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (1.0.2)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (2.6.1)
Requirement already satisfied: babel>=1.3 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (2.10.3)
Requirement already satisfied: requests>=2.5.0 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (2.23.0)
Requirement already satisfied: sphinxcontrib-qthelp in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (1.0.3)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in /usr/local/lib/python3.7/dist-packages (from sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (1.1.5)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (3.8.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.5.0->sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.5.0->sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.5.0->sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.5.0->sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (3.0.4)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.7/dist-packages (from statsmodels>=0.8.0->feature-engine==0.3.0) (0.5.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->sphinx>=3.0->numpydoc>=0.6.0->feature-engine==0.3.0) (3.0.9)

In [ ]:
from feature_engine import imputation as imp

In [17]:
#Contoh 1 - Imputasi END OF TAIL
#Import EndTailImputer


#from feature_engine.imputation import EndTailImputer


#Membuat imputer
imputer = EndTailImputer(imputation_method='gaussian', tail='right')

#Fit imputer ke set 
imputer.fit(data)

#Mengubah data
test_t = imputer.transform(data)

ImportError: ignored

In [ ]:
#Contoh 1 - Imputasi END OF TAIL
#Tampilkan data

test_t

Setelah dilakukan imputasi, nilai umur yang ada pada baris di indeks= 2 sudah terisi dengan nilai.

### Imputasi Frequent Category/Modus

Imputasi frequent category/Modus merupakan teknik untuk menggantikan nilai/data hilang dan digunakan bagi tipe data kategori.Cocok untuk data dengan missing at random.

In [ ]:
#Contoh 1 - Imputasi Frequent Category/Modus
#Import SimpleImputer dari sklearn.impute

from sklearn.impute import SimpleImputer

In [ ]:
#Contoh 1 - Imputasi Frequent Category/Modus
#Masukkan data

make = {'make' : ['Ford', 'Ford', 'Fiat', 'BMW', 'Ford', 'Kia', np.nan, 'Fiat', 'Ford', np.nan, 'Kia']}

#Ubah menjadi dataframe

data = pd.DataFrame(make)

#Tampilkan nilai variabel 'make' dalam bentuk dataframe

data

Tampak pada variabel 'make' terdapat nilai yang hilang (NaN), misalkan nilai yang ada pada baris di indeks= 6.

In [ ]:
#Contoh 1 - Imputasi Frequent Category/Modus
#Mengatasi missing value dengan frequent category / modus

imp = SimpleImputer(strategy='most_frequent')

In [ ]:
#Contoh 1 - Imputasi Frequent Category/Modus
#Tampilkan hasil imputasi

imp.fit_transform(data)

Setelah dilakukan imputasi, variabel 'make' pada baris di indeks= 6 telah terisi dengan nilai yang merupakan nilai modus dari data tersebut.

### Imputasi Random Sample 

Imputasi Random Sample merupakan teknik untuk menggantikan nilai/data hilang dan digunakan bagi tipe data kategori. Cocok untuk data missing at random. Imputasi ini menggantikan missing value dengan nilai lain dalam distribusi yang sama dari variabel asli.

In [ ]:
#Contoh 1 - Imputasi Random Sample
#Import randomsample imputer

from feature_engine.imputation import RandomSampleImputer

# masukkan data dan ubah menjadi dataframe

data = {'Gender' : ['Male', 'Male', np.nan, 'Female', 'Male', np.nan, 'Female'],
       'Age' : [29, np.nan, 43, 25, 34, 50, np.nan]}

#Data dalam bentuk dataframe

df = pd.DataFrame(data)

#Tampilkan data dalam bentuk dataframe
df

Pada data, tampak nilai yang hilang, misalkan pada data baris dengan indeks= 1 dan di kolom Age.

In [ ]:
#Contoh 1 - Imputasi Random Sample
#Buat imputernya
imputer = RandomSampleImputer(random_state = 29)

#Fit imputer ke set 
imputer.fit(df)

#Mengubah data
test_t = imputer.transform(df)

In [ ]:
#Contoh 1 - Imputasi Random Sample
#Tampilkan data hasil imputasi

test_t

Setelah dilakukan imputasi, tampak pada baris di indeks= 1 dan di kolom Age telah memiliki nilai.

### Imputasi Nilai Nol/Konstanta

Cara lain yang dapat dilakukan untuk menggantikan nilai yang hilang adalah dengan imputasi nilai nol/konstanta. Teknik ini cocok untuk variabel kategorik.

In [ ]:
#Contoh 1 - Imputasi Nilai Nol/Konstanta
#Masukkan  data

umur = {'umur' : [29, 43,  np.nan, 25, 34, np.nan, 50]}

#Ubah ke dataframe

data = pd.DataFrame(umur)

#Tampilkan nilai yang ada pada variabel 'umur' dalam bentuk dataframe 'data'

data

Tampak pada variabel 'umur' terdapat nilai yang hilang (NaN), misalkan nilai umur yang ada pada baris di indeks= 2.

In [ ]:
#Contoh 1 - Imputasi Nilai Nol/Konstanta
#Mengatasi nilai missing value dengan imputasi suka-suka
#Nilai suka-suka yang diberikan pada contoh adalah 99

data.fillna(0)

Setelah dilakukan imputasi nilai nol, data umur pada baris 2 telah memiliki nilai yaitu 0 (nol)

### Imputasi Regresi: Deterministik
**Sumber** : kaggle

Imputasi regresi deterministik adalah teknik mengganti missing value dengan prediksi yang tepat dari model regresi. Teknik ini tidak mempertimbangkan variasi acak di sekitar kemiringan (slope regresi).

Lengkapi library seperti matplotlib, seaborn, missingno, dan sklearn
Jika belum terinstall di Python, maka lakukan instalasi library terlebih dahulu.

<div class="alert alert-block alert-danger">
<b>Catatan : </b>Jika belum pernah instal library, gunakan perintah berikut secara inline atau melalui terminal.
    <ol>
    <li>!pip install matplotlib</li>
    <li>!pip install seaborn</li>
    <li>!pip install missingno</li>
    </ol>
</div>

In [ ]:
#Import library

import matplotlib.pyplot as plt
import seaborn as sns
import missingno as mno
from sklearn import linear_model

%matplotlib inline

**Fungsi: %matplotlib inline**

digunakan agar output dari perintah plotting ditampilkan inline di dalam frontend seperti notebook Jupyter, tepat di bawah sel kode yang memproduksinya. Plot yang dihasilkan kemudian akan disimpan dalam dokumen notebook.

In [ ]:
#Menentukan nilai yang hilang
#Memuat dataset dengan nama diabetes.csv

df = pd.read_csv("diabetes.csv")

#Tampilkan data teratas sebanyak 3 (tiga) baris data

df.head(3)

In [ ]:
#Melihat info dari dataset diabetes.csv

df.info()

In [ ]:
#Menghitung nilai statistik

df.describe()

In [ ]:
#Memilih kolom tertentu berdasarkan lokasi
#Fungsi df.loc[] digunakan untuk memilih table berdasarkan lokasi
#Nilai pada kolom 0.0 merupakan missing value (NaN)

df.loc[df["Glucose"] == 0.0, "Glucose"] = np.NAN
df.loc[df["BloodPressure"] == 0.0, "BloodPressure"] = np.NAN
df.loc[df["SkinThickness"] == 0.0, "SkinThickness"] = np.NAN
df.loc[df["Insulin"] == 0.0, "Insulin"] = np.NAN
df.loc[df["BMI"] == 0.0, "BMI"] = np.NAN

#Menghitung nilai null dari dataframe, dan hanya 5 (lima) kolom dengan menambahkan [1:6]

df.isnull().sum()[1:6]

In [ ]:
#Membuat matriks dengan ukuran yang diinginkan

mno.matrix(df, figsize = (20, 6))

#Fungsi figsize digunakan untuk menentukan ukuran figure

In [ ]:
#Menggunakan Regresi untuk memperhitungkan data yang hilang
#Kolom dapat ditentukan berdasarkan kebutuhan

missing_columns = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

In [ ]:
def random_imputation(df, feature):

    number_missing = df[feature].isnull().sum()
    observed_values = df.loc[df[feature].notnull(), feature]
    df.loc[df[feature].isnull(), feature + '_imp'] = np.random.choice(observed_values, number_missing, replace = True)
    
    return df

In [ ]:
for feature in missing_columns:
    df[feature + '_imp'] = df[feature]
    df = random_imputation(df, feature)

In [ ]:
# Deterministic Regression Imputation

deter_data = pd.DataFrame(columns = ["Det" + name for name in missing_columns])

for feature in missing_columns:
        
    deter_data["Det" + feature] = df[feature + "_imp"]
    parameters = list(set(df.columns) - set(missing_columns) - {feature + '_imp'})
    
    # Buat model Regresi Linier untuk memperkirakan data yang hilang
    
    model = linear_model.LinearRegression()
    model.fit(X = df[parameters], y = df[feature + '_imp'])
    
    # amati bahwa kita menyimpan indeks data yang hilang dari kerangka data asli
    
    deter_data.loc[df[feature].isnull(), "Det" + feature] = model.predict(df[parameters])[df[feature].isnull()]

In [ ]:
# membuat matriks

mno.matrix(deter_data, figsize = (20,5))

In [ ]:
# membuat chart

sns.set()
fig, axes = plt.subplots(nrows = 2, ncols = 2)
fig.set_size_inches(8, 8)

for index, variable in enumerate(["Insulin", "SkinThickness"]):
    sns.histplot(df[variable].dropna(), kde = False, ax = axes[index, 0])
    sns.histplot(deter_data["Det" + variable], kde = False, ax = axes[index, 0], color = 'red')
    
    sns.boxplot(data = pd.concat([df[variable], deter_data["Det" + variable]], axis = 1),
                ax = axes[index, 1])
    
plt.tight_layout()

In [ ]:
#Tampilkan nilai perhitungan statistika untuk kolom tertentu

pd.concat([df[["Insulin", "SkinThickness"]], deter_data[["DetInsulin", "DetSkinThickness"]]], axis = 1).describe().T

### Imputasi Regresi: Stokastik
**Sumber** : kaggle

Menambahkan fitur “random error” sehingga reproduksi korelasi X-Y lebih tepat.

In [ ]:
#Import library

import matplotlib.pyplot as plt
import seaborn as sns
import missingno as mno
from sklearn import linear_model

%matplotlib inline

In [ ]:
#Menentukan nilai yang hilang

df = pd.read_csv("diabetes.csv")
df.head(3)

In [ ]:
#Melihat info dari data frame

df.info()

In [ ]:
#Menghitung data statistik

df.describe()

In [ ]:
#Memilih kolom tertentu berdasarkan lokasi
#Fungsi df.loc[] digunakan untuk memilih table berdasarkan lokasi
#Nilai pada kolom 0.0 merupakan missing value (NaN)

df.loc[df["Glucose"] == 0.0, "Glucose"] = np.NAN
df.loc[df["BloodPressure"] == 0.0, "BloodPressure"] = np.NAN
df.loc[df["SkinThickness"] == 0.0, "SkinThickness"] = np.NAN
df.loc[df["Insulin"] == 0.0, "Insulin"] = np.NAN
df.loc[df["BMI"] == 0.0, "BMI"] = np.NAN

#Menghitung nilai null dari dataframe, dan hanya 5 (lima) kolom dengan menambahkan [1:6]

df.isnull().sum()[1:6]

In [ ]:
# membuat matriks

mno.matrix(df, figsize = (20, 6))

In [ ]:
#Menggunakan Regresi untuk memperhitungkan data yang hilang
#Memilih kolom tertentu

missing_columns = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

In [ ]:
def random_imputation(df, feature):

    number_missing = df[feature].isnull().sum()
    observed_values = df.loc[df[feature].notnull(), feature]
    df.loc[df[feature].isnull(), feature + '_imp'] = np.random.choice(observed_values, number_missing, replace = True)
    
    return df

In [ ]:
for feature in missing_columns:
    df[feature + '_imp'] = df[feature]
    df = random_imputation(df, feature)

In [ ]:
#Stochastic Regression Imputation

random_data = pd.DataFrame(columns = ["Ran" + name for name in missing_columns])

for feature in missing_columns:
        
    random_data["Ran" + feature] = df[feature + '_imp']
    parameters = list(set(df.columns) - set(missing_columns) - {feature + '_imp'})
    
    model = linear_model.LinearRegression()
    model.fit(X = df[parameters], y = df[feature + '_imp'])
    
    #Kesalahan Standar dari perkiraan regresi sama dengan std() dari kesalahan setiap perkiraan
    
    predict = model.predict(df[parameters])
    std_error = (predict[df[feature].notnull()] - df.loc[df[feature].notnull(), feature + '_imp']).std()
    
    #Amati bahwa kita menyimpan indeks data yang hilang dari kerangka data asli
    random_predict = np.random.normal(size = df[feature].shape[0], 
                                      loc = predict, 
                                      scale = std_error)
    random_data.loc[(df[feature].isnull()) & (random_predict > 0), "Ran" + feature] = random_predict[(df[feature].isnull()) & 
                                                                            (random_predict > 0)]

In [ ]:
#Membuat chart

sns.set()
fig, axes = plt.subplots(nrows = 2, ncols = 2)
fig.set_size_inches(8, 8)

for index, variable in enumerate(["Insulin", "SkinThickness"]):
    sns.histplot(df[variable].dropna(), kde = False, ax = axes[index, 0])
    sns.histplot(random_data["Ran" + variable], kde = False, ax = axes[index, 0], color = 'red')
    axes[index, 0].set(xlabel = variable + " / " + variable + '_imp')
    
    sns.boxplot(data = pd.concat([df[variable], random_data["Ran" + variable]], axis = 1),
                ax = axes[index, 1])
    
    plt.tight_layout()

In [ ]:
#Tampilkan nilai perhitungan statistika untuk kolom tertentu

pd.concat([df[["Insulin", "SkinThickness"]], random_data[["RanInsulin", "RanSkinThickness"]]], axis = 1).describe().T

## Trimming vs Winsorizing
---

Trimming adalah teknik untuk menghapus outlier dari dataset.
Windsorizing adalah mengganti outlier dari dataset dengan nilai persentil setiap ujung/batas atas dan bawah.

In [ ]:
#Import library scipy

import numpy as np
from scipy.stats.mstats import winsorize
from scipy.stats.mstats import trima

# Masukkan array berisi 1 - 10

a = np.array([10, 4, 9, 8, 5, 3, 7, 2, 1, 6])

In [ ]:
#Winsorize akan mengganti 10% nilai terendah dan 20% nilai tinggi

wins = winsorize(a, limits=[0.1, 0.2])
wins

In [ ]:
#Trima akan memotong nilai dengan batas tertentu

trims = trima(a, limits=(2,8))
print(trims)

## Binning
---

Proses mengubah fungsi, model dan variabel kontinu menjadi diskret (data kontinu di Ukur (measured), data kontinu di Hitung (counted)).

In [ ]:
#Load/muat dataset dengan nama bins.csv

df = pd.read_csv('bins.csv')

#Tampilkan isi dataset
df

In [ ]:
# Membuat array yang berisi sejumlah angka dengan jarak yang sama dengan linspace()
#linspace --> numpy.linspace(nilai minimum, nilai maksimum, jumlah elemen)

bins = np.linspace(min(df['Harga']), max(df['Harga']), 4)
bins

In [ ]:
# bins --> mengelompokkan data
# binning dengan cut()
# membuat kategori harga

df = pd.read_csv('bins.csv')
kategori = ['Murah', 'Standar', 'Mahal']
df['Harga Binned'] = pd.cut(df['Harga'], bins, labels=kategori, include_lowest=True)

#Tampilkan data
df

In [ ]:
#Menggunakan interval range untuk binning data dengan cut()

df = pd.read_csv('bins.csv')
interval_range = pd.interval_range(start=0, freq=10000, end=100000) 
df['Harga Binned 2'] = pd.cut(df['Harga'], bins = interval_range)

#Tampilkan data
df

In [ ]:
#Binning dengan qcut()

df = pd.read_csv('bins.csv')
df['Harga Binned 3'] = pd.qcut(df['Harga'], 3)

#Tampilkan data
df

## Scaling (Penskalaan)
---

Data numerik (biasanya) tidak memiliki range. 
COntoh: pada range  “Usia” vs range “Gaji” tidak sama (karakteristik berbeda). Usia memiliki rentang dari 1 sampai 150 (dalam tahun), sedangkan Gaji memiliki rentang dari 10 ribu sampai 100 ribu (dalam dolar). Untuk itu membandingkan perlu scaling.

In [ ]:
#Import library

from sklearn.preprocessing import Normalizer

#Load/memuat/membaca data 
data = pd.read_csv("scalling.csv")

#Buat objek skalar dengan normalizer
max_abs = Normalizer(norm = 'l2')

#Sesuaikan scaler dengan data 
max_abs.fit(data)

#Mengubah data
train_scaled = max_abs.transform(data)

In [ ]:
#Tampilkan hasil

train_scaled

## Scaling: Normalisasi
---
Teknik penskalaan dengan nilai-nilai digeser dan diubah skalanya sehingga nilainya berkisar antara 0 dan 1 atau rentang [0,1]

In [ ]:
# import pandas dan numpy

import pandas as pd
import numpy as np

# membaca data
data = pd.read_csv("scalling.csv")

#Tampilkan data
data

In [ ]:
#Menghitung mean
means = data.mean(axis = 0)

# menghitung max - min
max_min = data.max(axis = 0) - data.min(axis = 0)

# menerapkan transformasi ke data
train_scaled = (data - means) / max_min

In [ ]:
#Tampilkan hasil

train_scaled

## Scaling: Standardisasi
---

Berfokus pada mengubah data mentah menjadi informasi yang dapat digunakan sebelum dianalisis. Merupakan teknik yang menskalakan data shingga memiliki mean = 0 dan standar deviasi =1.

In [ ]:
#Import library

import pandas as pd
from sklearn.preprocessing import StandardScaler

#Load/memuat/membaca data
data = pd.read_csv("scalling.csv")

#Tampilkan data
data

In [ ]:
#Buat objek scaler
scaler = StandardScaler()

#Sesuaikan scaler dengan data
scaler.fit(data)

#Mengubah data kereta 
train_scaled = scaler.transform(data)

In [ ]:
#Tampilkan hasil

train_scaled